project:
  name: quickstart-microfocus-operations-orchestration
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  oo-in-new-vpc:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BastionAccessCIDR: 0.0.0.0/0
      DBMasterPassword: $[taskcat_genpass_10S]
      DBMasterPasswordConfirm: $[taskcat_getval_DBMasterPassword]
      DBMasterUsername: oodbadmin
      ELBAccessCIDR: $[taskcat_getval_PublicSubnet1CIDR]
      ELBScheme: internal
      LicenseAgreement: I agree
      LinuxBastionKeyPairName: myKeyForBastion
      NotificationTrigger: 'false'
      OOCentralDBName: $[taskcat_genpass_8A]
      OOCentralNodesSize: '2'
      OOCentralOOPass: $[taskcat_genpass_15S]
      OOCentralOOPassConfirm: $[taskcat_getval_OOCentralOOPass]
      OOCentralPass: $[taskcat_genpass_15S]
      OOCentralPassConfirm: $[taskcat_getval_OOCentralPass]
      OOCentralRootPass: $[taskcat_genpass_16S]
      OOCentralRootPassConfirm: $[taskcat_getval_OOCentralRootPass]
      OODesignerDBName: $[taskcat_genpass_9A]
      OODesignerOOPass: $[taskcat_genpass_16S]
      OODesignerOOPassConfirm: $[taskcat_getval_OODesignerOOPass]
      OODesignerPass: $[taskcat_genpass_16S]
      OODesignerPassConfirm: $[taskcat_getval_OODesignerPass]
      OODesignerRootPass: $[taskcat_genpass_15S]
      OODesignerRootPassConfirm: $[taskcat_getval_OODesignerRootPass]
      OODesignerTrigger: 'true'
      OOKeyPairName: myKey
      OperatorEmail: someone@domain.org
      PrivateSubnet1CIDR: 12.0.0.0/19
      PrivateSubnet2CIDR: 12.0.32.0/19
      PublicSubnet1CIDR: 12.0.128.0/20
      PublicSubnet2CIDR: 12.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-microfocus-operations-orchestration/
      S3BucketNameForCluster: $[taskcat_getval_QSS3BucketName]
      S3KeyPrefixForCluster: $[taskcat_getval_QSS3KeyPrefix]
      VPCCIDR: 12.0.0.0/16
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/microfocus-oo-master-template.json
