global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-microfocus-operations-orchestration
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-microfocus-operations-orchestrationt1:
    parameter_input: quickstart-microfocus-operations-orchestration-example-params1.json
    template_file: quickstart-microfocus-operations-orchestration-example1.template
  quickstart-microfocus-operations-orchestrationt2:
    parameter_input: quickstart-microfocus-operations-orchestration-example-params2.json
    template_file: quickstart-microfocus-operations-orchestration-example2.template
